jobs:
  - name: development
    max_in_flight: 1
    plan:
      - get: dataworks-aws-ucfs-stub
        trigger: true
      - get: dataworks-aws-ucfs-stub-dev
        trigger: true
      - get: dw-al2-hardened-ami
        trigger: true
      - .: (( inject meta.plan.terraform-bootstrap ))
        input_mapping:
          dataworks-aws-ucfs-stub: dataworks-aws-ucfs-stub-dev     
      - .: (( inject meta.plan.terraform-apply )) 
        input_mapping:
          dataworks-aws-ucfs-stub: dataworks-aws-ucfs-stub-dev    
      - .: (( inject meta.plan.terraform-plan ))
        input_mapping:
          dataworks-aws-ucfs-stub: dataworks-aws-ucfs-stub-dev
