jobs:
  - name: dataworks-aws-ucfs-stub-integration
    max_in_flight: 1
    plan:
      - get: dataworks-aws-ucfs-stub
        trigger: true
        passed:
          - dataworks-aws-ucfs-stub-qa
      - .: (( inject meta.plan.terraform-bootstrap ))
      - .: (( inject meta.plan.terraform-apply ))
        params:
          TF_WORKSPACE: 'integration'
      - .: (( inject meta.plan.terraform-plan ))
        params:
          TF_WORKSPACE: 'integration'
