jobs:
  - name: preprod
    max_in_flight: 1
    plan:
      - get: dataworks-aws-ucfs-stub
        trigger: true
        passed:
          - integration
      - get: dw-al2-hardened-ami
        trigger: false
        passed:
          - integration
      - .: (( inject meta.plan.terraform-bootstrap ))
      - .: (( inject meta.plan.terraform-destroy ))
        params:
          TF_WORKSPACE: 'preprod'
