jobs:
  - name: production
    max_in_flight: 1
    plan:
      - get: dataworks-aws-ucfs-stub
        trigger: true
        passed:
          - preprod
      - get: dw-al2-hardened-ami
        trigger: false
        passed:
          - preprod
      - .: (( inject meta.plan.terraform-bootstrap ))
      - .: (( inject meta.plan.terraform-destroy ))
        params:
          TF_WORKSPACE: 'production'
