jobs:
  - name: qa
    max_in_flight: 1
    plan:
      - get: dataworks-aws-ucfs-stub
        trigger: true
      - get: dw-al2-hardened-ami
        trigger: false
      - .: (( inject meta.plan.terraform-bootstrap ))
      - .: (( inject meta.plan.terraform-destroy ))
        params:
          TF_WORKSPACE: 'qa'
